; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61219.0 

	TITLE	D:\Git\GitHubProject\Raven\Mini_Projet_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
