; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	D:\Git\GitHubProject\Mini_Projet_Raven_IA\Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
